on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: |
        mkdir -p build
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/logmon-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload Release Assets
      run: |
        gh release upload ${{ github.event.release.tag_name }} build/logmon-${{ matrix.goos }}-${{ matrix.goarch }}* --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}